require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails'
require 'capistrano/sidekiq'
# require 'capistrano/sidekiq/monit'
require 'capistrano3/unicorn'
require 'capistrano/nginx'
