product:
  reviews_count: 5
  related_group: 2

pagination:
  products: 10
  posts: 10
  users: 10
  cities: 10
  orders: 10

mailers:
  orders:
    created:
      admin:
        header: На сайте оформлен заказ
    paid:
      admin:
        header: Оплачен заказ
    approved:
      user:
        header: Ваш заказ одобрен
        body:
          payment_system: 'Вы можете его оплатить по ссылке: %{payment_link}'
          receive: Оплата для курьера
          cashless: Оплата для юр. лиц

shop:
  default:
    from: 'no-replay@sterep-shop.ru'
    shop_name: Интернет-магазин Стереошоп
    phone: '8 (812) 499-49-20'
    feedback_email: post@artelectronics.ru
    address: 'Санкт-Петербург, Каменноостровский пр., 14Б, офис 2-Н.'
    timetable: 'Мы работаем по будням с 10-00 до 18-00'
    host: sterep-shop.ru
  feedback:
    to: 'post@artelectronics.ru'
    subject: Обратная связь
  newletter:
    subject: Новостная рассылка
  order:
    admins: 'post@artelectronics.ru, farid@artelectronics.ru, yana@artelectronics.ru'
    subject:
      created: Оформлен заказ

carrierwave:
  extension_white_list:
    files: ['csv', 'xml', 'doc', 'xls', 'docx', 'txt', 'xlsx', 'pdf']
    accept: '.csv, .xml, .doc, .docx, .txt, .xlsx, .pdf'
    photos: ['jpg', 'jpeg', 'png']

central_bank:
  urls:
    daily: 'http://www.cbr.ru/scripts/XML_daily.asp'
    range: 'http://www.cbr.ru/scripts/XML_dynamic.asp'
  currency_code:
    eur: 'R01239'

yandex_cashbox:
  url:
    test: https://demomoney.yandex.ru/eshop.xml
    production: https://demomoney.yandex.ru/eshop.xml
  shop_id: 42821
  shop_password: 6MtsWFPQmsshRXcZ
  currency_code: 643
  production_ips: ['77.75.157.166', '77.75.157.170']
