product:
  reviews_count: 5
  related_group: 2

pagination:
  products: 10
  posts: 10

shop:
  feedback:
    to: 'test@shop.ru'
    subject: Default Subject
    from: 'shop@shop.ru'
  newletter:
    subject: Default subject
