product:
  reviews_count: 5
  related_group: 2

pagination:
  products: 10
  posts: 10
  users: 10
  cities: 10

shop:
  feedback:
    to: 'test@shop.ru'
    subject: Default Subject
    from: 'shop@shop.ru'
  newletter:
    subject: Default subject

carrierwave:
  extension_white_list:
    files: ['csv', 'xml', 'doc', 'xls']
    photos: ['jpg', 'jpeg', 'png']
