---
:verbose: true
:concurrency: 2
:namespace: stereo_shop_development

:queues:
  - [critical, 7]
  - [default,  5]
  - [single,   5]
  - [mailer,  10]
  - [low,      1]

:limits:
  single: 1
  low: 1
